name: hello workflow
on:
  push:
    branches: [master]
    paths:
      - "**.html"
      - "**.md"
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello, world!"
      - name: say goodbye
        run: echo "Goodbye, world!"

  task-1:
    runs-on: ubuntu-latest
    steps:
      - name: task 1
        run: echo "This is task 1"
