name: Portfolio
on:
    push:
        branches: [daily-assignment]
        paths:
            - "**.html"
permissions:
    pages: write # to deploy to GitHub Pages
    id-token: write # to authenticate with GitHub Pages
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deploy-pages.outputs.page_url}}
        steps:
            # sets the workspace for the tasks to be executed
            - name: checkout-code
              uses: actions/checkout@v4 # sets the workspace for the tasks to be executed
            - name: Setup GitHub Pages
              uses: actions/configure-pages@v4
            - name: Upload static files
              with:
                  path: .
              uses: actions/upload-pages-artifact@v4
            - name: Deploy to GitHub Pages
              id: deploy-pages
              uses: actions/deploy-pages@v4
